"""Remove role and email, add nickname to users

Revision ID: 1e04f2532bb5
Revises: add_binding_table
Create Date: 2025-11-07 04:09:44.457690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1e04f2532bb5'
down_revision: Union[str, None] = 'add_binding_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nickname', sa.String(length=100), nullable=False))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', mysql.ENUM('CHEF', 'CUSTOMER', collation='utf8mb4_unicode_ci'), nullable=False))
    op.add_column('users', sa.Column('full_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))
    op.add_column('users', sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'nickname')
    # ### end Alembic commands ###
